project:
  type: website
  output-dir: docs

website:
  title: "Vagish Hemmige"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching       
      - href: presentation.qmd
        text: Presentations
      - href: abstracts.qmd
        text: Abstracts
      - href: manuscripts.qmd
        text: Manuscripts
      - href: Projects.qmd
        text: Projects
      - href: about.qmd
        text: About
      - text: "GitHub"
        href: https://github.com/VagishHemmige
        target: _blank

format:
  html:
    theme: cosmo
    toc: true
    css: styles.scss
