project:
  type: website
  output-dir: docs

website:
  title: "Vagish Hemmige"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "GitHub"
        href: https://github.com/VagishHemmige
        target: _blank

format:
  html:
    theme: cosmo
    toc: false
